# Common definitions

GDC ?= gdc
DMD ?= dmd
LLVMDIR ?= llvm
SOURCE_WILDCARDS = \
	src/sdc/*.d \
	src/sdc/ast/*.d \
	src/sdc/parser/*.d \
	src/sdc/gen/*.d \
	src/sdc/java/*.d \
	src/sdc/interpreter/*.d \
	src/d/ast/*.d \
	src/d/parser/*.d
