# Common definitions

GDC ?= gdc
DMD ?= dmd
SOURCE_WILDCARDS = \
	src/sdc/*.d \
	src/sdc/ast/*.d \
	src/sdc/pass/*.d \
	src/d/*.d \
	src/d/ast/*.d \
	src/d/backend/*.d \
	src/d/parser/*.d \
	src/d/semantic/*.d \
	src/d/processor/*.d \
	src/util/*.d \
	src/etc/linux/*.d
