include makefile.common

DFLAGS = -w -debug -g -unittest -Iimport $(FLAGS)
SOURCE = $(SOURCE_WILDCARDS)
OBJ = bin\sdc.obj
EXE = bin\sdc.exe

LIBLLVM = $(LLVMDIR)\llvm-2.9.lib

all: $(EXE)

$(EXE):
	@mkdir -p bin
	$(DMD) $(DFLAGS) -of"$@" $(SOURCE) "$(LIBLLVM)"

clean:
	rm $(EXE) $(OBJ)
