GDC=gdc
DFLAGS=-g -Wall -Werror -funittest -I./import -Isrc
SOURCE=$(wildcard src/sdc/*.d src/sdc/ast/*.d src/sdc/parser/*.d src/sdc/gen/*.d src/sdc/extract/*.d)
OBJS=$(SOURCE:.d=.o)
EXE=sdc

sdc: $(OBJS)
	$(GDC) $(OBJS) -lLLVM-2.8 -o $(EXE)

%.o: %.d $(SOURCE)
	$(GDC) $(DFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(EXE)

