include makefile.common

DFLAGS = -g -Wall -Werror -funittest -I./import -Isrc -m32 -version=SDCCOMPILER
SOURCE = $(wildcard $SOURCE_WILDCARDS)
OBJS = $(SOURCE:.d=.o)
EXE = sdc

LIBLLVM=$(LLVMDIR)/*.a
sdc: $(OBJS)
	$(GDC) $(OBJS) -lstdc++ -ldl ${LIBLLVM} -m32 -o $(EXE)

%.o: %.d $(SOURCE)
	$(GDC) $(DFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(EXE)

