DMD ?= dmd
LLVMDIR ?= llvm

DFLAGS=-w -debug -g -unittest -Iimport
SOURCE=src/sdc/*.d src/sdc/ast/*.d src/sdc/parser/*.d src/sdc/gen/*.d src/sdc/java/*.d
EXE=bin\sdc.exe

LIBLLVM=$(LLVMDIR)\llvm-2.9.lib

all: $(EXE)

$(EXE):
	@mkdir -p bin
	$(DMD) $(DFLAGS) -of"$@" $(SOURCE) "$(LIBLLVM)"