# Common definitions

GDC ?= gdc
DMD ?= dmd
SOURCE_WILDCARDS = \
	src/sdc/*.d \
	src/sdc/ast/*.d \
	src/sdc/parser/*.d \
	src/sdc/pass/*.d \
	src/d/ast/*.d \
	src/d/parser/*.d \
	src/d/pass/*.d \
	src/util/*.d
