PLATFORM_X64_ASM_SRC = $(wildcard platform/x64/*.asm)
PLATFORM_ASM_SRC += $(PLATFORM_X64_ASM_SRC)

PLATFORM_X64_ASM_OBJ = $(PLATFORM_X64_ASM_SRC:platform/%.asm=obj/%.o)
PLATFORM_ASM_OBJ += $(PLATFORM_X64_ASM_OBJ)

# Add the objects to expected variables.
LIBSDRT_PLATFORM_OBJ += $(PLATFORM_X64_ASM_OBJ)
LIBSDMD_PLATFORM_OBJ += $(PLATFORM_X64_ASM_OBJ)
