// NOTE: Assertions have been autogenerated by tools/update_sdc_test_checks.py UTC_ARGS: --version 6
// RUN: %sdc %s -O2 -S --emit-llvm -o - | FileCheck %s
module atomic;

import d.sync.atomic;

// CHECK-LABEL: define i32 @_D6atomic10doFetchAddFMOPOS1d4sync6atomic6AtomicTTkZ6AtomickZk(
// CHECK-SAME: ptr nofree captures(none) [[ARG_X:%.*]], i32 [[ARG_N:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = atomicrmw add ptr [[ARG_X]], i32 [[ARG_N]] seq_cst, align 4
// CHECK-NEXT:    ret i32 [[TMP0]]
//
uint doFetchAdd(shared Atomic!uint* x, uint n) {
	return x.fetchAdd(n);
}

// CHECK-LABEL: define i32 @_D6atomic10doFetchSubFMOPOS1d4sync6atomic6AtomicTTkZ6AtomickZk(
// CHECK-SAME: ptr nofree captures(none) [[ARG_X:%.*]], i32 [[ARG_N:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = atomicrmw sub ptr [[ARG_X]], i32 [[ARG_N]] seq_cst, align 4
// CHECK-NEXT:    ret i32 [[TMP0]]
//
uint doFetchSub(shared Atomic!uint* x, uint n) {
	return x.fetchSub(n);
}

// CHECK-LABEL: define i32 @_D6atomic10doFetchAndFMOPOS1d4sync6atomic6AtomicTTkZ6AtomickZk(
// CHECK-SAME: ptr nofree captures(none) [[ARG_X:%.*]], i32 [[ARG_N:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = atomicrmw and ptr [[ARG_X]], i32 [[ARG_N]] seq_cst, align 4
// CHECK-NEXT:    ret i32 [[TMP0]]
//
uint doFetchAnd(shared Atomic!uint* x, uint n) {
	return x.fetchAnd(n);
}

// CHECK-LABEL: define i32 @_D6atomic9doFetchOrFMOPOS1d4sync6atomic6AtomicTTkZ6AtomickZk(
// CHECK-SAME: ptr nofree captures(none) [[ARG_X:%.*]], i32 [[ARG_N:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = atomicrmw or ptr [[ARG_X]], i32 [[ARG_N]] seq_cst, align 4
// CHECK-NEXT:    ret i32 [[TMP0]]
//
uint doFetchOr(shared Atomic!uint* x, uint n) {
	return x.fetchOr(n);
}

// CHECK-LABEL: define i32 @_D6atomic10doFetchXorFMOPOS1d4sync6atomic6AtomicTTkZ6AtomickZk(
// CHECK-SAME: ptr nofree captures(none) [[ARG_X:%.*]], i32 [[ARG_N:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = atomicrmw xor ptr [[ARG_X]], i32 [[ARG_N]] seq_cst, align 4
// CHECK-NEXT:    ret i32 [[TMP0]]
//
uint doFetchXor(shared Atomic!uint* x, uint n) {
	return x.fetchXor(n);
}

// CHECK-LABEL: define i32 @_D6atomic6doLoadFMOPOS1d4sync6atomic6AtomicTTkZ6AtomicZk(
// CHECK-SAME: ptr nofree captures(none) [[ARG_X:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load atomic i32, ptr [[ARG_X]] seq_cst, align 4
// CHECK-NEXT:    ret i32 [[TMP0]]
//
uint doLoad(shared Atomic!uint* x) {
	return x.load();
}

// CHECK-LABEL: define void @_D6atomic7doStoreFMOPOS1d4sync6atomic6AtomicTTkZ6AtomickZv(
// CHECK-SAME: ptr nofree captures(none) [[ARG_X:%.*]], i32 [[ARG_N:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    store atomic i32 [[ARG_N]], ptr [[ARG_X]] seq_cst, align 4
// CHECK-NEXT:    ret void
//
void doStore(shared Atomic!uint* x, uint n) {
	x.store(n);
}

// CHECK-LABEL: define i1 @_D6atomic5doCasFMOPOS1d4sync6atomic6AtomicTTkZ6AtomickZb(
// CHECK-SAME: ptr nofree captures(none) [[ARG_X:%.*]], i32 [[ARG_N:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = cmpxchg ptr [[ARG_X]], i32 0, i32 [[ARG_N]] seq_cst seq_cst, align 4
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i1 } [[TMP0]], 1
// CHECK-NEXT:    ret i1 [[TMP1]]
//
bool doCas(shared Atomic!uint* x, uint n) {
	uint expected = 0;
	return x.cas(expected, n);
}

// CHECK-LABEL: define i1 @_D6atomic9doCasWeakFMOPOS1d4sync6atomic6AtomicTTkZ6AtomickZb(
// CHECK-SAME: ptr nofree captures(none) [[ARG_X:%.*]], i32 [[ARG_N:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = cmpxchg weak ptr [[ARG_X]], i32 0, i32 [[ARG_N]] seq_cst seq_cst, align 4
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i1 } [[TMP0]], 1
// CHECK-NEXT:    ret i1 [[TMP1]]
//
bool doCasWeak(shared Atomic!uint* x, uint n) {
	uint expected = 0;
	return x.casWeak(expected, n);
}
