// NOTE: Assertions have been autogenerated by tools/update_sdc_test_checks.py UTC_ARGS: --version 6
// RUN: %sdc %s -g -O2 -S --emit-llvm -o - | FileCheck %s
module dbg;

enum E {
	A,
	B,
	S,
}

class A {
	// CHECK-LABEL: define noundef i32 @_D3dbg1A3fooFC3dbg1AZE3dbg1E(
	// CHECK-SAME: ptr nofree readnone captures(none) [[THIS:%.*]]) #[[ATTR0:[0-9]+]] !dbg [[DBG10:![0-9]+]] {
	// CHECK-NEXT:  [[ENTRY:.*:]]
	// CHECK-NEXT:    ret i32 0
	//
	E foo() {
		return E.A;
	}
}

class B : A {
	// CHECK-LABEL: define noundef i32 @_D3dbg1B3fooFC3dbg1BZE3dbg1E(
	// CHECK-SAME: ptr nofree readnone captures(none) [[THIS:%.*]]) #[[ATTR0]] !dbg [[DBG24:![0-9]+]] {
	// CHECK-NEXT:  [[ENTRY:.*:]]
	// CHECK-NEXT:    ret i32 1
	//
	override E foo() {
		return E.B;
	}
}

struct S {
	// CHECK-LABEL: define noundef i32 @_D3dbg1S3fooFKS3dbg1SZE3dbg1E(
	// CHECK-SAME: ptr nofree readnone captures(none) [[THIS:%.*]]) local_unnamed_addr #[[ATTR0]] !dbg [[DBG31:![0-9]+]] {
	// CHECK-NEXT:  [[ENTRY:.*:]]
	// CHECK-NEXT:    ret i32 2
	//
	E foo() {
		return E.S;
	}
}

// CHECK-LABEL: define i32 @_D3dbg3fooFMS3dbg1SC3dbg1AC3dbg1BZk(
// CHECK-SAME: [[S3DBG1S:%.*]] [[ARG_S:%.*]], ptr [[ARG_A:%.*]], ptr [[ARG_B:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] !dbg [[DBG37:![0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[ARG_A]], align 8, !dbg [[DBG41:![0-9]+]]
// CHECK-NEXT:    [[VTBL:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP0]], i64 24, !dbg [[DBG41]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[VTBL]], align 8, !dbg [[DBG41]]
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i32 [[TMP1]](ptr nonnull [[ARG_A]]), !dbg [[DBG41]]
// CHECK-NEXT:    [[TMP3:%.*]] = add i32 [[TMP2]], 2, !dbg [[DBG42:![0-9]+]]
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[ARG_B]], align 8, !dbg [[DBG43:![0-9]+]]
// CHECK-NEXT:    [[VTBL1:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP4]], i64 24, !dbg [[DBG43]]
// CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[VTBL1]], align 8, !dbg [[DBG43]]
// CHECK-NEXT:    [[TMP6:%.*]] = tail call i32 [[TMP5]](ptr nonnull [[ARG_B]]), !dbg [[DBG43]]
// CHECK-NEXT:    [[TMP7:%.*]] = add i32 [[TMP3]], [[TMP6]], !dbg [[DBG42]]
// CHECK-NEXT:    ret i32 [[TMP7]]
//
uint foo(S s, A a, B b) {
	return s.foo() + a.foo() + b.foo();
}

//.
// CHECK: [[META0:![0-9]+]] = distinct !DICompileUnit(language: DW_LANG_D, file: [[META1:![0-9]+]], producer: "The Snazzy D compiler.", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: [[META2:![0-9]+]], splitDebugInlining: false)
// CHECK: [[META1]] = !DIFile(filename: "{{.*}}dbg.d", directory: {{.*}})
// CHECK: [[META2]] = !{[[META3:![0-9]+]], [[META3]], [[META3]]}
// CHECK: [[META3]] = !DICompositeType(tag: DW_TAG_enumeration_type, name: "E", scope: [[META4:![0-9]+]], file: [[META1]], line: 5, baseType: [[META5:![0-9]+]], size: 32, align: 32, elements: [[META6:![0-9]+]])
// CHECK: [[META4]] = !DIModule(scope: [[META1]], name: "dbg")
// CHECK: [[META5]] = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
// CHECK: [[META6]] = !{[[META7:![0-9]+]], [[META8:![0-9]+]], [[META9:![0-9]+]]}
// CHECK: [[META7]] = !DIEnumerator(name: "A", value: 0)
// CHECK: [[META8]] = !DIEnumerator(name: "B", value: 1)
// CHECK: [[META9]] = !DIEnumerator(name: "S", value: 2)
// CHECK: [[DBG10]] = distinct !DISubprogram(name: "foo", linkageName: "_D3dbg1A3fooFC3dbg1AZE3dbg1E", scope: [[META11:![0-9]+]], file: [[META1]], line: 17, type: [[META21:![0-9]+]], spFlags: DISPFlagDefinition, unit: [[META0]])
// CHECK: [[META11]] = !DICompositeType(tag: DW_TAG_class_type, name: "A", scope: [[META4]], file: [[META1]], line: 11, baseType: [[META12:![0-9]+]], size: 64, align: 64, elements: [[META19:![0-9]+]], vtableHolder: [[META12]], identifier: "C3dbg1A")
// CHECK: [[META12]] = distinct !DICompositeType(tag: DW_TAG_class_type, name: "Object", scope: [[META14:![0-9]+]], file: [[META13:![0-9]+]], line: 19, baseType: [[META12]], size: 64, align: 64, elements: [[META15:![0-9]+]], vtableHolder: [[META12]], identifier: "C6object6Object")
// CHECK: [[META13]] = !DIFile(filename: "{{.*}}object.d", directory: {{.*}})
// CHECK: [[META14]] = !DIModule(scope: [[META13]], name: "object")
// CHECK: [[META15]] = !{[[META16:![0-9]+]]}
// CHECK: [[META16]] = !DIDerivedType(tag: DW_TAG_member, name: "__vtbl", scope: [[META12]], file: [[META13]], line: 19, baseType: [[META17:![0-9]+]], size: 64, align: 64)
// CHECK: [[META17]] = !DIDerivedType(tag: DW_TAG_pointer_type, name: "void*", baseType: [[META18:![0-9]+]], size: 64, align: 64, dwarfAddressSpace: 0)
// CHECK: [[META18]] = !DIBasicType(name: "void")
// CHECK: [[META19]] = !{[[META20:![0-9]+]]}
// CHECK: [[META20]] = !DIDerivedType(tag: DW_TAG_inheritance, scope: [[META11]], baseType: [[META12]], extraData: i32 0)
// CHECK: [[META21]] = !DISubroutineType(types: [[META22:![0-9]+]])
// CHECK: [[META22]] = !{[[META3]], [[META23:![0-9]+]]}
// CHECK: [[META23]] = !DIDerivedType(tag: DW_TAG_reference_type, baseType: [[META11]])
// CHECK: [[DBG24]] = distinct !DISubprogram(name: "foo", linkageName: "_D3dbg1B3fooFC3dbg1BZE3dbg1E", scope: [[META25:![0-9]+]], file: [[META1]], line: 28, type: [[META28:![0-9]+]], spFlags: DISPFlagDefinition, unit: [[META0]])
// CHECK: [[META25]] = !DICompositeType(tag: DW_TAG_class_type, name: "B", scope: [[META4]], file: [[META1]], line: 22, baseType: [[META11]], size: 64, align: 64, elements: [[META26:![0-9]+]], vtableHolder: [[META11]], identifier: "C3dbg1B")
// CHECK: [[META26]] = !{[[META27:![0-9]+]]}
// CHECK: [[META27]] = !DIDerivedType(tag: DW_TAG_inheritance, scope: [[META25]], baseType: [[META11]], extraData: i32 0)
// CHECK: [[META28]] = !DISubroutineType(types: [[META29:![0-9]+]])
// CHECK: [[META29]] = !{[[META3]], [[META30:![0-9]+]]}
// CHECK: [[META30]] = !DIDerivedType(tag: DW_TAG_reference_type, baseType: [[META25]])
// CHECK: [[DBG31]] = distinct !DISubprogram(name: "foo", linkageName: "_D3dbg1S3fooFKS3dbg1SZE3dbg1E", scope: [[META32:![0-9]+]], file: [[META1]], line: 39, type: [[META34:![0-9]+]], spFlags: DISPFlagDefinition, unit: [[META0]])
// CHECK: [[META32]] = !DICompositeType(tag: DW_TAG_structure_type, name: "S", scope: [[META4]], file: [[META1]], line: 33, align: 8, elements: [[META33:![0-9]+]], identifier: "S3dbg1S")
// CHECK: [[META33]] = !{}
// CHECK: [[META34]] = !DISubroutineType(types: [[META35:![0-9]+]])
// CHECK: [[META35]] = !{[[META3]], [[META36:![0-9]+]]}
// CHECK: [[META36]] = !DIDerivedType(tag: DW_TAG_reference_type, baseType: [[META32]])
// CHECK: [[DBG37]] = distinct !DISubprogram(name: "foo", linkageName: "_D3dbg3fooFMS3dbg1SC3dbg1AC3dbg1BZk", scope: [[META4]], file: [[META1]], line: 59, type: [[META38:![0-9]+]], spFlags: DISPFlagDefinition, unit: [[META0]])
// CHECK: [[META38]] = !DISubroutineType(types: [[META39:![0-9]+]])
// CHECK: [[META39]] = !{[[META40:![0-9]+]], [[META32]], [[META23]], [[META30]]}
// CHECK: [[META40]] = !DIBasicType(name: "uint", size: 32, encoding: DW_ATE_unsigned)
// CHECK: [[DBG41]] = !DILocation(line: 60, column: 19, scope: [[DBG37]])
// CHECK: [[DBG42]] = !DILocation(line: 60, column: 9, scope: [[DBG37]])
// CHECK: [[DBG43]] = !DILocation(line: 60, column: 29, scope: [[DBG37]])
//.
