// NOTE: Assertions have been autogenerated by tools/update_sdc_test_checks.py UTC_ARGS: --version 6
// RUN: %sdc %s -O2 -S --emit-llvm -o - | FileCheck %s
module downcast;

class A {}

class B : A {}

final class C : B {}

// CHECK-LABEL: define ptr @_D8downcast11downcastToAFMC6object6ObjectZC8downcast1A(
// CHECK-SAME: ptr nofree readonly captures(address_is_null, ret: address, provenance) [[ARG_O:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[ARG_O]], null
// CHECK-NEXT:    br i1 [[TMP0]], label %[[_D6OBJECT19__SD_CLASS_DOWNCASTFMC6OBJECT6OBJECTC6OBJECT9CLASSINFOZC6OBJECT6OBJECT_EXIT:.*]], label %[[ENDIF_I:.*]]
// CHECK:       [[ENDIF_I]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[ARG_O]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP1]], i64 8
// CHECK-NEXT:    [[DOTUNPACK_I:%.*]] = load i64, ptr [[TMP2]], align 8
// CHECK-NEXT:    [[DOTNOT_I_NOT:%.*]] = icmp eq i64 [[DOTUNPACK_I]], 0
// CHECK-NEXT:    br i1 [[DOTNOT_I_NOT]], label %[[_D6OBJECT19__SD_CLASS_DOWNCASTFMC6OBJECT6OBJECTC6OBJECT9CLASSINFOZC6OBJECT6OBJECT_EXIT]], label %[[BOUND_OK_I:.*]]
// CHECK:       [[BOUND_OK_I]]:
// CHECK-NEXT:    [[DOTELT11_I:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP1]], i64 16
// CHECK-NEXT:    [[DOTUNPACK12_I:%.*]] = load ptr, ptr [[DOTELT11_I]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[DOTUNPACK12_I]], align 8
// CHECK-NEXT:    [[DOTNOT13_I:%.*]] = icmp eq ptr [[TMP3]], @C8downcast1A.vtbl
// CHECK-NEXT:    [[TMP4:%.*]] = select i1 [[DOTNOT13_I]], ptr [[ARG_O]], ptr null
// CHECK-NEXT:    br label %[[_D6OBJECT19__SD_CLASS_DOWNCASTFMC6OBJECT6OBJECTC6OBJECT9CLASSINFOZC6OBJECT6OBJECT_EXIT]]
// CHECK:       [[_D6OBJECT19__SD_CLASS_DOWNCASTFMC6OBJECT6OBJECTC6OBJECT9CLASSINFOZC6OBJECT6OBJECT_EXIT]]:
// CHECK-NEXT:    [[COMMON_RET_OP_I:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ null, %[[ENDIF_I]] ], [ [[TMP4]], %[[BOUND_OK_I]] ]
// CHECK-NEXT:    ret ptr [[COMMON_RET_OP_I]]
//
auto downcastToA(Object o) {
	return cast(A) o;
}

// CHECK-LABEL: define ptr @_D8downcast11downcastToBFMC6object6ObjectZC8downcast1B(
// CHECK-SAME: ptr nofree readonly captures(address_is_null, ret: address, provenance) [[ARG_O:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[ARG_O]], null
// CHECK-NEXT:    br i1 [[TMP0]], label %[[_D6OBJECT19__SD_CLASS_DOWNCASTFMC6OBJECT6OBJECTC6OBJECT9CLASSINFOZC6OBJECT6OBJECT_EXIT:.*]], label %[[ENDIF_I:.*]]
// CHECK:       [[ENDIF_I]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[ARG_O]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP1]], i64 8
// CHECK-NEXT:    [[DOTUNPACK_I:%.*]] = load i64, ptr [[TMP2]], align 8
// CHECK-NEXT:    [[DOTNOT_I:%.*]] = icmp ugt i64 [[DOTUNPACK_I]], 1
// CHECK-NEXT:    br i1 [[DOTNOT_I]], label %[[BOUND_OK_I:.*]], label %[[_D6OBJECT19__SD_CLASS_DOWNCASTFMC6OBJECT6OBJECTC6OBJECT9CLASSINFOZC6OBJECT6OBJECT_EXIT]]
// CHECK:       [[BOUND_OK_I]]:
// CHECK-NEXT:    [[DOTELT11_I:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP1]], i64 16
// CHECK-NEXT:    [[DOTUNPACK12_I:%.*]] = load ptr, ptr [[DOTELT11_I]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw i8, ptr [[DOTUNPACK12_I]], i64 8
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP3]], align 8
// CHECK-NEXT:    [[DOTNOT13_I:%.*]] = icmp eq ptr [[TMP4]], @C8downcast1B.vtbl
// CHECK-NEXT:    [[TMP5:%.*]] = select i1 [[DOTNOT13_I]], ptr [[ARG_O]], ptr null
// CHECK-NEXT:    br label %[[_D6OBJECT19__SD_CLASS_DOWNCASTFMC6OBJECT6OBJECTC6OBJECT9CLASSINFOZC6OBJECT6OBJECT_EXIT]]
// CHECK:       [[_D6OBJECT19__SD_CLASS_DOWNCASTFMC6OBJECT6OBJECTC6OBJECT9CLASSINFOZC6OBJECT6OBJECT_EXIT]]:
// CHECK-NEXT:    [[COMMON_RET_OP_I:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ null, %[[ENDIF_I]] ], [ [[TMP5]], %[[BOUND_OK_I]] ]
// CHECK-NEXT:    ret ptr [[COMMON_RET_OP_I]]
//
auto downcastToB(Object o) {
	return cast(B) o;
}

// CHECK-LABEL: define ptr @_D8downcast11downcastToCFMC6object6ObjectZC8downcast1C(
// CHECK-SAME: ptr nofree readonly captures(address_is_null, ret: address, provenance) [[ARG_O:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[ARG_O]], null
// CHECK-NEXT:    br i1 [[TMP0]], label %[[_D6OBJECT25__SD_FINAL_CLASS_DOWNCASTFMC6OBJECT6OBJECTC6OBJECT9CLASSINFOZC6OBJECT6OBJECT_EXIT:.*]], label %[[OR_RHS_I:.*]]
// CHECK:       [[OR_RHS_I]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[ARG_O]], align 8
// CHECK-NEXT:    [[DOTNOT_I:%.*]] = icmp eq ptr [[TMP1]], @C8downcast1C.vtbl
// CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[DOTNOT_I]], ptr [[ARG_O]], ptr null
// CHECK-NEXT:    br label %[[_D6OBJECT25__SD_FINAL_CLASS_DOWNCASTFMC6OBJECT6OBJECTC6OBJECT9CLASSINFOZC6OBJECT6OBJECT_EXIT]]
// CHECK:       [[_D6OBJECT25__SD_FINAL_CLASS_DOWNCASTFMC6OBJECT6OBJECTC6OBJECT9CLASSINFOZC6OBJECT6OBJECT_EXIT]]:
// CHECK-NEXT:    [[COMMON_RET_OP_I:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[TMP2]], %[[OR_RHS_I]] ]
// CHECK-NEXT:    ret ptr [[COMMON_RET_OP_I]]
//
auto downcastToC(Object o) {
	return cast(C) o;
}
