// NOTE: Assertions have been autogenerated by tools/update_sdc_test_checks.py UTC_ARGS: --version 6
// RUN: %sdc %s -S --emit-llvm -o - | FileCheck %s

//

// CHECK-LABEL: define i32 @_D12foreachloops18test_foreach_arrayFMG10iZi(
// CHECK-SAME: [10 x i32] [[ARG_ARR:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:    [[ARR:%.*]] = alloca [10 x i32], align 4
// CHECK-NEXT:    store [10 x i32] [[ARG_ARR]], ptr [[ARR]], align 4
// CHECK-NEXT:    [[SUM:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[TMP1:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[TMP2:%.*]] = alloca i32, align 4
// CHECK-NEXT:    br label %[[ENTRY:.*]]
// CHECK:       [[ENTRY]]:
// CHECK-NEXT:    store i32 0, ptr [[SUM]], align 4
// CHECK-NEXT:    store i64 0, ptr [[TMP1]], align 8
// CHECK-NEXT:    br label %[[LOOP_TEST:.*]]
// CHECK:       [[LOOP_CONTINUE:.*]]:
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = add i64 [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP4]], ptr [[TMP1]], align 8
// CHECK-NEXT:    br label %[[LOOP_TEST]]
// CHECK:       [[LOOP_TEST]]:
// CHECK-NEXT:    [[TMP5:%.*]] = load i64, ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = load [10 x i32], ptr [[ARR]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = icmp ult i64 [[TMP5]], 10
// CHECK-NEXT:    br i1 [[TMP7]], label %[[LOOP_BODY:.*]], label %[[LOOP_EXIT:.*]]
// CHECK:       [[LOOP_BODY]]:
// CHECK-NEXT:    [[TMP8:%.*]] = load i64, ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP9:%.*]] = icmp ult i64 [[TMP8]], 10
// CHECK-NEXT:    br i1 [[TMP9]], label %[[BOUND_OK:.*]], label %[[BOUND_FAIL:.*]], !prof [[PROF0:![0-9]+]]
// CHECK:       [[BOUND_FAIL]]:
// CHECK-NEXT:    call void @__sd_array_outofbounds({ i64, ptr } { i64 14, ptr @.str }, i32 54)
// CHECK-NEXT:    unreachable
// CHECK:       [[BOUND_OK]]:
// CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i32, ptr [[ARR]], i64 [[TMP8]]
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[TMP10]], align 4
// CHECK-NEXT:    store i32 [[TMP11]], ptr [[X]], align 4
// CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[X]], align 4
// CHECK-NEXT:    store i32 [[TMP12]], ptr [[TMP2]], align 4
// CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[TMP2]], align 4
// CHECK-NEXT:    [[TMP14:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[TMP2]], align 4
// CHECK-NEXT:    [[TMP16:%.*]] = add i32 [[TMP14]], [[TMP15]]
// CHECK-NEXT:    store i32 [[TMP16]], ptr [[SUM]], align 4
// CHECK-NEXT:    br label %[[LOOP_CONTINUE]]
// CHECK:       [[LOOP_EXIT]]:
// CHECK-NEXT:    [[TMP17:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    ret i32 [[TMP17]]
//
int test_foreach_array(int[10] arr) {
	int sum = 0;
	foreach (x; arr) {
		sum += x;
	}

	return sum;
}

// CHECK-LABEL: define i32 @_D12foreachloops18test_foreach_sliceFMAiZi(
// CHECK-SAME: { i64, ptr } [[ARG_SLICE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:    [[SLICE:%.*]] = alloca { i64, ptr }, align 8
// CHECK-NEXT:    store { i64, ptr } [[ARG_SLICE]], ptr [[SLICE]], align 8
// CHECK-NEXT:    [[SUM:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[TMP1:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[TMP2:%.*]] = alloca i32, align 4
// CHECK-NEXT:    br label %[[ENTRY:.*]]
// CHECK:       [[ENTRY]]:
// CHECK-NEXT:    store i32 0, ptr [[SUM]], align 4
// CHECK-NEXT:    store i64 0, ptr [[TMP1]], align 8
// CHECK-NEXT:    br label %[[LOOP_TEST:.*]]
// CHECK:       [[LOOP_CONTINUE:.*]]:
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = add i64 [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP4]], ptr [[TMP1]], align 8
// CHECK-NEXT:    br label %[[LOOP_TEST]]
// CHECK:       [[LOOP_TEST]]:
// CHECK-NEXT:    [[TMP5:%.*]] = load i64, ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw { i64, ptr }, ptr [[SLICE]], i32 0, i32 0
// CHECK-NEXT:    [[TMP7:%.*]] = load i64, ptr [[TMP6]], align 8
// CHECK-NEXT:    [[TMP8:%.*]] = icmp ult i64 [[TMP5]], [[TMP7]]
// CHECK-NEXT:    br i1 [[TMP8]], label %[[LOOP_BODY:.*]], label %[[LOOP_EXIT:.*]]
// CHECK:       [[LOOP_BODY]]:
// CHECK-NEXT:    [[TMP9:%.*]] = load { i64, ptr }, ptr [[SLICE]], align 8
// CHECK-NEXT:    [[DOTPTR:%.*]] = extractvalue { i64, ptr } [[TMP9]], 1
// CHECK-NEXT:    [[DOTLENGTH:%.*]] = extractvalue { i64, ptr } [[TMP9]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = load i64, ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP11:%.*]] = icmp ult i64 [[TMP10]], [[DOTLENGTH]]
// CHECK-NEXT:    br i1 [[TMP11]], label %[[BOUND_OK:.*]], label %[[BOUND_FAIL:.*]], !prof [[PROF0]]
// CHECK:       [[BOUND_FAIL]]:
// CHECK-NEXT:    call void @__sd_array_outofbounds({ i64, ptr } { i64 14, ptr @.str }, i32 113)
// CHECK-NEXT:    unreachable
// CHECK:       [[BOUND_OK]]:
// CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i32, ptr [[DOTPTR]], i64 [[TMP10]]
// CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[TMP12]], align 4
// CHECK-NEXT:    store i32 [[TMP13]], ptr [[X]], align 4
// CHECK-NEXT:    [[TMP14:%.*]] = load i32, ptr [[X]], align 4
// CHECK-NEXT:    store i32 [[TMP14]], ptr [[TMP2]], align 4
// CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[TMP2]], align 4
// CHECK-NEXT:    [[TMP16:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    [[TMP17:%.*]] = load i32, ptr [[TMP2]], align 4
// CHECK-NEXT:    [[TMP18:%.*]] = add i32 [[TMP16]], [[TMP17]]
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[SUM]], align 4
// CHECK-NEXT:    br label %[[LOOP_CONTINUE]]
// CHECK:       [[LOOP_EXIT]]:
// CHECK-NEXT:    [[TMP19:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    ret i32 [[TMP19]]
//
int test_foreach_slice(int[] slice) {
	int sum = 0;
	foreach (x; slice) {
		sum += x;
	}

	return sum;
}

// CHECK-LABEL: define i32 @_D12foreachloops18test_foreach_rangeFMZi(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:    [[SUM:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[TMP1:%.*]] = alloca i32, align 4
// CHECK-NEXT:    br label %[[ENTRY:.*]]
// CHECK:       [[ENTRY]]:
// CHECK-NEXT:    store i32 0, ptr [[SUM]], align 4
// CHECK-NEXT:    store i32 0, ptr [[I]], align 4
// CHECK-NEXT:    br label %[[LOOP_TEST:.*]]
// CHECK:       [[LOOP_CONTINUE:.*]]:
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = add i32 [[TMP2]], 1
// CHECK-NEXT:    store i32 [[TMP3]], ptr [[I]], align 4
// CHECK-NEXT:    br label %[[LOOP_TEST]]
// CHECK:       [[LOOP_TEST]]:
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = icmp slt i32 [[TMP4]], 5
// CHECK-NEXT:    br i1 [[TMP5]], label %[[LOOP_BODY:.*]], label %[[LOOP_EXIT:.*]]
// CHECK:       [[LOOP_BODY]]:
// CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[TMP1]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[TMP1]], align 4
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[TMP1]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = add i32 [[TMP8]], [[TMP9]]
// CHECK-NEXT:    store i32 [[TMP10]], ptr [[SUM]], align 4
// CHECK-NEXT:    br label %[[LOOP_CONTINUE]]
// CHECK:       [[LOOP_EXIT]]:
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    ret i32 [[TMP11]]
//
int test_foreach_range() {
	int sum = 0;
	foreach (i; 0 .. 5) {
		sum += i;
	}

	return sum;
}

// CHECK-LABEL: define i32 @_D12foreachloops26test_foreach_reverse_rangeFMZi(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:    [[SUM:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[TMP1:%.*]] = alloca i32, align 4
// CHECK-NEXT:    br label %[[ENTRY:.*]]
// CHECK:       [[ENTRY]]:
// CHECK-NEXT:    store i32 0, ptr [[SUM]], align 4
// CHECK-NEXT:    store i32 5, ptr [[I]], align 4
// CHECK-NEXT:    br label %[[LOOP_CONTINUE:.*]]
// CHECK:       [[LOOP_CONTINUE]]:
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = add i32 [[TMP2]], -1
// CHECK-NEXT:    store i32 [[TMP3]], ptr [[I]], align 4
// CHECK-NEXT:    [[TMP4:%.*]] = icmp sgt i32 [[TMP2]], 0
// CHECK-NEXT:    br i1 [[TMP4]], label %[[LOOP_BODY:.*]], label %[[LOOP_EXIT:.*]]
// CHECK:       [[LOOP_BODY]]:
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[TMP1]], align 4
// CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[TMP1]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[TMP1]], align 4
// CHECK-NEXT:    [[TMP9:%.*]] = add i32 [[TMP7]], [[TMP8]]
// CHECK-NEXT:    store i32 [[TMP9]], ptr [[SUM]], align 4
// CHECK-NEXT:    br label %[[LOOP_CONTINUE]]
// CHECK:       [[LOOP_EXIT]]:
// CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    ret i32 [[TMP10]]
//
int test_foreach_reverse_range() {
	int sum = 0;
	foreach_reverse (i; 0 .. 5) {
		sum += i;
	}

	return sum;
}

//.
// CHECK: [[PROF0]] = !{!"branch_weights", i32 2000, i32 0}
//.
