// NOTE: Assertions have been autogenerated by tools/update_sdc_test_checks.py UTC_ARGS: --version 6
// RUN: %sdc %s -O2 -S --emit-llvm -o - | FileCheck %s
module intrinsics;

import sdc.intrinsics;

// CHECK-LABEL: define void @_D10intrinsics8doAllocaFMmZv(
// CHECK-SAME: i64 [[ARG_S:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = alloca i8, i64 [[ARG_S]], align 16
// CHECK-NEXT:    call void @_D10intrinsics8doAlloca7consumeFMPvZv(ptr nonnull [[TMP0]])
// CHECK-NEXT:    ret void
//
void doAlloca(size_t s) {
	auto a = alloca(s);

	static void consume(void*);
	consume(a);
}

// CHECK-LABEL: define range(i64 0, 121) i64 @_D10intrinsics10doPopCountFMhtkmZm(
// CHECK-SAME: i8 [[ARG_N1:%.*]], i16 [[ARG_N2:%.*]], i32 [[ARG_N3:%.*]], i64 [[ARG_N4:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call range(i8 0, 9) i8 @llvm.ctpop.i8(i8 [[ARG_N1]])
// CHECK-NEXT:    [[TMP1:%.*]] = zext nneg i8 [[TMP0]] to i32
// CHECK-NEXT:    [[TMP2:%.*]] = tail call range(i16 0, 17) i16 @llvm.ctpop.i16(i16 [[ARG_N2]])
// CHECK-NEXT:    [[TMP3:%.*]] = zext nneg i16 [[TMP2]] to i32
// CHECK-NEXT:    [[TMP4:%.*]] = add nuw nsw i32 [[TMP3]], [[TMP1]]
// CHECK-NEXT:    [[TMP5:%.*]] = tail call range(i32 0, 33) i32 @llvm.ctpop.i32(i32 [[ARG_N3]])
// CHECK-NEXT:    [[TMP6:%.*]] = add nuw nsw i32 [[TMP4]], [[TMP5]]
// CHECK-NEXT:    [[TMP7:%.*]] = zext nneg i32 [[TMP6]] to i64
// CHECK-NEXT:    [[TMP8:%.*]] = tail call range(i64 0, 65) i64 @llvm.ctpop.i64(i64 [[ARG_N4]])
// CHECK-NEXT:    [[TMP9:%.*]] = add nuw nsw i64 [[TMP8]], [[TMP7]]
// CHECK-NEXT:    ret i64 [[TMP9]]
//
ulong doPopCount(ubyte n1, ushort n2, uint n3, ulong n4) {
	return popCount(n1) + popCount(n2) + popCount(n3) + popCount(n4);
}

// CHECK-LABEL: define range(i64 0, 121) i64 @_D10intrinsics19doCountLeadingZerosFMhtkmZm(
// CHECK-SAME: i8 [[ARG_N1:%.*]], i16 [[ARG_N2:%.*]], i32 [[ARG_N3:%.*]], i64 [[ARG_N4:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call range(i8 0, 9) i8 @llvm.ctlz.i8(i8 [[ARG_N1]], i1 false)
// CHECK-NEXT:    [[TMP1:%.*]] = zext nneg i8 [[TMP0]] to i64
// CHECK-NEXT:    [[TMP2:%.*]] = tail call range(i16 0, 17) i16 @llvm.ctlz.i16(i16 [[ARG_N2]], i1 false)
// CHECK-NEXT:    [[TMP3:%.*]] = zext nneg i16 [[TMP2]] to i64
// CHECK-NEXT:    [[TMP4:%.*]] = tail call range(i32 0, 33) i32 @llvm.ctlz.i32(i32 [[ARG_N3]], i1 false)
// CHECK-NEXT:    [[TMP5:%.*]] = zext nneg i32 [[TMP4]] to i64
// CHECK-NEXT:    [[TMP6:%.*]] = tail call range(i64 0, 65) i64 @llvm.ctlz.i64(i64 [[ARG_N4]], i1 false)
// CHECK-NEXT:    [[TMP7:%.*]] = add nuw nsw i64 [[TMP3]], [[TMP1]]
// CHECK-NEXT:    [[TMP8:%.*]] = add nuw nsw i64 [[TMP7]], [[TMP5]]
// CHECK-NEXT:    [[TMP9:%.*]] = add nuw nsw i64 [[TMP8]], [[TMP6]]
// CHECK-NEXT:    ret i64 [[TMP9]]
//
ulong doCountLeadingZeros(ubyte n1, ushort n2, uint n3, ulong n4) {
	auto a = countLeadingZeros(n1) + countLeadingZeros(n2);
	auto b = countLeadingZeros(n3) + countLeadingZeros(n4);
	return a + b;
}

// CHECK-LABEL: define range(i64 0, 121) i64 @_D10intrinsics20doCountTrailingZerosFMhtkmZm(
// CHECK-SAME: i8 [[ARG_N1:%.*]], i16 [[ARG_N2:%.*]], i32 [[ARG_N3:%.*]], i64 [[ARG_N4:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call range(i8 0, 9) i8 @llvm.cttz.i8(i8 [[ARG_N1]], i1 false)
// CHECK-NEXT:    [[TMP1:%.*]] = zext nneg i8 [[TMP0]] to i64
// CHECK-NEXT:    [[TMP2:%.*]] = tail call range(i16 0, 17) i16 @llvm.cttz.i16(i16 [[ARG_N2]], i1 false)
// CHECK-NEXT:    [[TMP3:%.*]] = zext nneg i16 [[TMP2]] to i64
// CHECK-NEXT:    [[TMP4:%.*]] = tail call range(i32 0, 33) i32 @llvm.cttz.i32(i32 [[ARG_N3]], i1 false)
// CHECK-NEXT:    [[TMP5:%.*]] = zext nneg i32 [[TMP4]] to i64
// CHECK-NEXT:    [[TMP6:%.*]] = tail call range(i64 0, 65) i64 @llvm.cttz.i64(i64 [[ARG_N4]], i1 false)
// CHECK-NEXT:    [[TMP7:%.*]] = add nuw nsw i64 [[TMP3]], [[TMP1]]
// CHECK-NEXT:    [[TMP8:%.*]] = add nuw nsw i64 [[TMP7]], [[TMP5]]
// CHECK-NEXT:    [[TMP9:%.*]] = add nuw nsw i64 [[TMP8]], [[TMP6]]
// CHECK-NEXT:    ret i64 [[TMP9]]
//
ulong doCountTrailingZeros(ubyte n1, ushort n2, uint n3, ulong n4) {
	auto a = countTrailingZeros(n1) + countTrailingZeros(n2);
	auto b = countTrailingZeros(n3) + countTrailingZeros(n4);
	return a + b;
}

// CHECK-LABEL: define i64 @_D10intrinsics7doBswapFMtkmZm(
// CHECK-SAME: i16 [[ARG_N1:%.*]], i32 [[ARG_N2:%.*]], i64 [[ARG_N3:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i16 @llvm.bswap.i16(i16 [[ARG_N1]])
// CHECK-NEXT:    [[TMP1:%.*]] = zext i16 [[TMP0]] to i32
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i32 @llvm.bswap.i32(i32 [[ARG_N2]])
// CHECK-NEXT:    [[TMP3:%.*]] = add i32 [[TMP2]], [[TMP1]]
// CHECK-NEXT:    [[TMP4:%.*]] = zext i32 [[TMP3]] to i64
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i64 @llvm.bswap.i64(i64 [[ARG_N3]])
// CHECK-NEXT:    [[TMP6:%.*]] = add i64 [[TMP5]], [[TMP4]]
// CHECK-NEXT:    ret i64 [[TMP6]]
//
ulong doBswap(ushort n1, uint n2, ulong n3) {
	return bswap(n1) + bswap(n2) + bswap(n3);
}

// CHECK-LABEL: define i1 @_D10intrinsics5doCasFMPkkkZb(
// CHECK-SAME: ptr nofree captures(none) [[ARG_PTR:%.*]], i32 [[ARG_OLD:%.*]], i32 [[ARG_VAL:%.*]]) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = cmpxchg ptr [[ARG_PTR]], i32 [[ARG_OLD]], i32 [[ARG_VAL]] seq_cst seq_cst, align 4
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i1 } [[TMP0]], 1
// CHECK-NEXT:    ret i1 [[TMP1]]
//
bool doCas(uint* ptr, uint old, uint val) {
	auto cr = cas(ptr, old, val);
	return cr.success;
}

// CHECK-LABEL: define i1 @_D10intrinsics9doCasWeakFMPkkkZb(
// CHECK-SAME: ptr nofree captures(none) [[ARG_PTR:%.*]], i32 [[ARG_OLD:%.*]], i32 [[ARG_VAL:%.*]]) local_unnamed_addr #[[ATTR4]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = cmpxchg weak ptr [[ARG_PTR]], i32 [[ARG_OLD]], i32 [[ARG_VAL]] seq_cst seq_cst, align 4
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i1 } [[TMP0]], 1
// CHECK-NEXT:    ret i1 [[TMP1]]
//
bool doCasWeak(uint* ptr, uint old, uint val) {
	auto cr = casWeak(ptr, old, val);
	return cr.success;
}

// CHECK-LABEL: define i64 @_D10intrinsics18doReadCycleCounterFMZm(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR5:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.readcyclecounter()
// CHECK-NEXT:    ret i64 [[TMP0]]
//
ulong doReadCycleCounter() {
	return readCycleCounter();
}

// CHECK-LABEL: define ptr @_D10intrinsics18doReadFramePointerFMZPv(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call ptr @llvm.frameaddress.p0(i32 0)
// CHECK-NEXT:    ret ptr [[TMP0]]
//
void* doReadFramePointer() {
	return readFramePointer();
}
