// NOTE: Assertions have been autogenerated by tools/update_sdc_test_checks.py UTC_ARGS: --version 6
// RUN: %sdc %s -S -O2 --emit-llvm -o - | FileCheck %s
module memaccess;

shared uint a;

// CHECK-LABEL: define i32 @_D9memaccess3fooFMOPOkkZk(
// CHECK-SAME: ptr nofree captures(none) [[ARG_PTR:%.*]], i32 [[ARG_VAL:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    store atomic i32 [[ARG_VAL]], ptr [[ARG_PTR]] seq_cst, align 4
// CHECK-NEXT:    store atomic i32 [[ARG_VAL]], ptr @_D9memaccess1aOk seq_cst, align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load atomic i32, ptr @_D9memaccess1aOk seq_cst, align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load atomic i32, ptr [[ARG_PTR]] seq_cst, align 4
// CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[TMP1]], [[TMP0]]
// CHECK-NEXT:    ret i32 [[TMP2]]
//
uint foo(shared uint* ptr, uint val) {
	*ptr = val;
	a = val;
	return a + *ptr;
}
