// NOTE: Assertions have been autogenerated by tools/update_sdc_test_checks.py UTC_ARGS: --version 6
// RUN: %sdc %s -O2 -S --emit-llvm -o - | FileCheck %s
module pgo;

import sdc.intrinsics;

void doSomething();

// CHECK-LABEL: define void @_D3pgo11checkExpectFMbbZv(
// CHECK-SAME: i1 [[ARG_B1:%.*]], i1 [[ARG_B2:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    br i1 [[ARG_B1]], label %[[THEN:.*]], label %[[ENDIF:.*]], !prof [[PROF0:![0-9]+]]
// CHECK:       [[THEN]]:
// CHECK-NEXT:    tail call void @_D3pgo11doSomethingFMZv()
// CHECK-NEXT:    br label %[[ENDIF]]
// CHECK:       [[ENDIF]]:
// CHECK-NEXT:    br i1 [[ARG_B2]], label %[[THEN1:.*]], label %[[ENDIF2:.*]], !prof [[PROF1:![0-9]+]]
// CHECK:       [[THEN1]]:
// CHECK-NEXT:    tail call void @_D3pgo11doSomethingFMZv()
// CHECK-NEXT:    br label %[[ENDIF2]]
// CHECK:       [[ENDIF2]]:
// CHECK-NEXT:    ret void
//
void checkExpect(bool b1, bool b2) {
	if (expect(b1, true)) {
		doSomething();
	}

	if (expect(b2, false)) {
		doSomething();
	}
}

// CHECK-LABEL: define void @_D3pgo11checkLikelyFMbZv(
// CHECK-SAME: i1 [[ARG_B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    br i1 [[ARG_B]], label %[[THEN:.*]], label %[[ENDIF:.*]], !prof [[PROF0]]
// CHECK:       [[THEN]]:
// CHECK-NEXT:    tail call void @_D3pgo11doSomethingFMZv()
// CHECK-NEXT:    br label %[[ENDIF]]
// CHECK:       [[ENDIF]]:
// CHECK-NEXT:    ret void
//
void checkLikely(bool b) {
	if (likely(b)) {
		doSomething();
	}
}

// CHECK-LABEL: define void @_D3pgo13checkUnlikelyFMbZv(
// CHECK-SAME: i1 [[ARG_B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    br i1 [[ARG_B]], label %[[THEN:.*]], label %[[ENDIF:.*]], !prof [[PROF1]]
// CHECK:       [[THEN]]:
// CHECK-NEXT:    tail call void @_D3pgo11doSomethingFMZv()
// CHECK-NEXT:    br label %[[ENDIF]]
// CHECK:       [[ENDIF]]:
// CHECK-NEXT:    ret void
//
void checkUnlikely(bool b) {
	if (unlikely(b)) {
		doSomething();
	}
}

//.
// CHECK: [[PROF0]] = !{!"branch_weights", !"expected", i32 2000, i32 1}
// CHECK: [[PROF1]] = !{!"branch_weights", !"expected", i32 1, i32 2000}
//.
