// NOTE: Assertions have been autogenerated by tools/update_sdc_test_checks.py UTC_ARGS: --version 6
// RUN: %sdc %s -S --emit-llvm -o - | FileCheck %s
module prepostincdec;

// Pre-inc evaluates to the new value.
// CHECK-LABEL: define i32 @_D13prepostincdec6preincFMKiZi(
// CHECK-SAME: ptr [[X:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:    br label %[[ENTRY:.*]]
// CHECK:       [[ENTRY]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[TMP1]], 1
// CHECK-NEXT:    store i32 [[TMP2]], ptr [[X]], align 4
// CHECK-NEXT:    ret i32 [[TMP2]]
//
int preinc(ref int x) {
	return ++x;
}

// Post-inc evaluates to the old value via a temporary.
// CHECK-LABEL: define i32 @_D13prepostincdec7postincFMKiZi(
// CHECK-SAME: ptr [[X:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:    br label %[[ENTRY:.*]]
// CHECK:       [[ENTRY]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[TMP1]], 1
// CHECK-NEXT:    store i32 [[TMP2]], ptr [[X]], align 4
// CHECK-NEXT:    ret i32 [[TMP1]]
//
int postinc(ref int x) {
	return x++;
}

// CHECK-LABEL: define i32 @_D13prepostincdec6predecFMKiZi(
// CHECK-SAME: ptr [[X:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:    br label %[[ENTRY:.*]]
// CHECK:       [[ENTRY]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[TMP1]], -1
// CHECK-NEXT:    store i32 [[TMP2]], ptr [[X]], align 4
// CHECK-NEXT:    ret i32 [[TMP2]]
//
int predec(ref int x) {
	return --x;
}

// CHECK-LABEL: define i32 @_D13prepostincdec7postdecFMKiZi(
// CHECK-SAME: ptr [[X:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:    br label %[[ENTRY:.*]]
// CHECK:       [[ENTRY]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[TMP1]], -1
// CHECK-NEXT:    store i32 [[TMP2]], ptr [[X]], align 4
// CHECK-NEXT:    ret i32 [[TMP1]]
//
int postdec(ref int x) {
	return x--;
}

// Pre-inc on pointers uses GEP and evaluates to the new pointer.
// CHECK-LABEL: define ptr @_D13prepostincdec9preincptrFMKPiZPi(
// CHECK-SAME: ptr [[P:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:    br label %[[ENTRY:.*]]
// CHECK:       [[ENTRY]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i32 1
// CHECK-NEXT:    store ptr [[TMP2]], ptr [[P]], align 8
// CHECK-NEXT:    ret ptr [[TMP2]]
//
int* preincptr(ref int* p) {
	return ++p;
}

// CHECK-LABEL: define ptr @_D13prepostincdec10postincptrFMKPiZPi(
// CHECK-SAME: ptr [[P:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:    br label %[[ENTRY:.*]]
// CHECK:       [[ENTRY]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i32 1
// CHECK-NEXT:    store ptr [[TMP2]], ptr [[P]], align 8
// CHECK-NEXT:    ret ptr [[TMP1]]
//
int* postincptr(ref int* p) {
	return p++;
}

// CHECK-LABEL: define ptr @_D13prepostincdec9predecptrFMKPiZPi(
// CHECK-SAME: ptr [[P:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:    br label %[[ENTRY:.*]]
// CHECK:       [[ENTRY]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i32 -1
// CHECK-NEXT:    store ptr [[TMP2]], ptr [[P]], align 8
// CHECK-NEXT:    ret ptr [[TMP2]]
//
int* predecptr(ref int* p) {
	return --p;
}

// CHECK-LABEL: define ptr @_D13prepostincdec10postdecptrFMKPiZPi(
// CHECK-SAME: ptr [[P:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:    br label %[[ENTRY:.*]]
// CHECK:       [[ENTRY]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i32 -1
// CHECK-NEXT:    store ptr [[TMP2]], ptr [[P]], align 8
// CHECK-NEXT:    ret ptr [[TMP1]]
//
int* postdecptr(ref int* p) {
	return p--;
}
