// NOTE: Assertions have been autogenerated by tools/update_sdc_test_checks.py UTC_ARGS: --version 6
// RUN: %sdc %s -S --emit-llvm -o - | FileCheck %s
module structabi;

struct S {
	ulong[4] parts;

	this(ulong n) {
		parts[3] = n;
	}

	// CHECK-LABEL: define ptr @_D9structabi1S8allocateFMmZPS9structabi1S(
	// CHECK-SAME: i64 [[ARG_N:%.*]]) #[[ATTR0:[0-9]+]] {
	// CHECK-NEXT:    [[N:%.*]] = alloca i64, align 8
	// CHECK-NEXT:    store i64 [[ARG_N]], ptr [[N]], align 8
	// CHECK-NEXT:    br label %[[ENTRY:.*]]
	// CHECK:       [[ENTRY]]:
	// CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[N]], align 8
	// CHECK-NEXT:    [[TMP2:%.*]] = call ptr @__sd_gc_alloc(i64 ptrtoint (ptr getelementptr ([[S9STRUCTABI1S:%.*]], ptr null, i32 1) to i64))
	// CHECK-NEXT:    [[TMP3:%.*]] = call [[S9STRUCTABI1S]] @[[_D9STRUCTABI1S6__CTORFMS9STRUCTABI1SMZS9STRUCTABI1S:[a-zA-Z0-9_$\"\\.-]*[a-zA-Z_$\"\\.-][a-zA-Z0-9_$\"\\.-]*]]([[S9STRUCTABI1S]] zeroinitializer, i64 [[TMP1]])
	// CHECK-NEXT:    store [[S9STRUCTABI1S]] [[TMP3]], ptr [[TMP2]], align 8
	// CHECK-NEXT:    ret ptr [[TMP2]]
	//
	static allocate(ulong n) {
		return new S(n);
	}
}

struct E {
	ulong[5] parts;
	uint moreparts;

	this(ulong n) {
		parts[4] = n;
		moreparts = 23;
	}

	// CHECK-LABEL: define ptr @_D9structabi1E8allocateFMmZPS9structabi1E(
	// CHECK-SAME: i64 [[ARG_N:%.*]]) #[[ATTR0]] {
	// CHECK-NEXT:    [[N:%.*]] = alloca i64, align 8
	// CHECK-NEXT:    store i64 [[ARG_N]], ptr [[N]], align 8
	// CHECK-NEXT:    br label %[[ENTRY:.*]]
	// CHECK:       [[ENTRY]]:
	// CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[N]], align 8
	// CHECK-NEXT:    [[TMP2:%.*]] = call ptr @__sd_gc_alloc(i64 ptrtoint (ptr getelementptr ([[S9STRUCTABI1E:%.*]], ptr null, i32 1) to i64))
	// CHECK-NEXT:    store [[S9STRUCTABI1E]] zeroinitializer, ptr [[TMP2]], align 8
	// CHECK-NEXT:    call void @_D9structabi1E6__ctorFMKS9structabi1EmZv(ptr [[TMP2]], i64 [[TMP1]])
	// CHECK-NEXT:    ret ptr [[TMP2]]
	//
	static allocate(ulong n) {
		return new E(n);
	}
}

struct F {
	E e;
	S s;

	this(ulong n) {
		this(n, n);
	}

	this(ulong a, ulong b) {
		e = E(a);
		s = S(b);
	}

	// CHECK-LABEL: define ptr @_D9structabi1F8allocateFMmZPS9structabi1F(
	// CHECK-SAME: i64 [[ARG_N:%.*]]) #[[ATTR0]] {
	// CHECK-NEXT:    [[N:%.*]] = alloca i64, align 8
	// CHECK-NEXT:    store i64 [[ARG_N]], ptr [[N]], align 8
	// CHECK-NEXT:    br label %[[ENTRY:.*]]
	// CHECK:       [[ENTRY]]:
	// CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[N]], align 8
	// CHECK-NEXT:    [[TMP2:%.*]] = call ptr @__sd_gc_alloc(i64 ptrtoint (ptr getelementptr ([[S9STRUCTABI1F:%.*]], ptr null, i32 1) to i64))
	// CHECK-NEXT:    store [[S9STRUCTABI1F]] zeroinitializer, ptr [[TMP2]], align 8
	// CHECK-NEXT:    call void @_D9structabi1F6__ctorFMKS9structabi1FmZv(ptr [[TMP2]], i64 [[TMP1]])
	// CHECK-NEXT:    ret ptr [[TMP2]]
	//
	static allocate(ulong n) {
		return new F(n);
	}
}
