// NOTE: Assertions have been autogenerated by tools/update_sdc_test_checks.py UTC_ARGS: --version 6
// RUN: %sdc %s -O2 -S --emit-llvm -o - | FileCheck %s
module unwind;

uint global;
void doSomething(uint);

// CHECK-LABEL: define void @_D6unwind7successFMZv(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[DOTPR:%.*]] = load i32, ptr @_D6unwind6globalk, align 4
// CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i32 [[DOTPR]], 5
// CHECK-NEXT:    br i1 [[TMP0]], label %[[LOOP_BODY:.*]], label %[[LOOP_EXIT:.*]]
// CHECK:       [[LOOP_BODY]]:
// CHECK-NEXT:    [[TMP1:%.*]] = phi i32 [ [[TMP3:%.*]], %[[LOOP_BODY]] ], [ [[DOTPR]], %[[ENTRY]] ]
// CHECK-NEXT:    tail call void @_D6unwind11doSomethingFMkZv(i32 [[TMP1]])
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr @_D6unwind6globalk, align 4
// CHECK-NEXT:    [[TMP3]] = add i32 [[TMP2]], 1
// CHECK-NEXT:    store i32 [[TMP3]], ptr @_D6unwind6globalk, align 4
// CHECK-NEXT:    [[TMP4:%.*]] = icmp ult i32 [[TMP3]], 5
// CHECK-NEXT:    br i1 [[TMP4]], label %[[LOOP_BODY]], label %[[LOOP_EXIT]]
// CHECK:       [[LOOP_EXIT]]:
// CHECK-NEXT:    ret void
//
void success() {
	while (global < 5) {
		scope(success) global++;

		doSomething(global);
	}
}

// CHECK-LABEL: define void @_D6unwind7failureFMZv(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] personality ptr @__sd_eh_personality {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    br label %[[LOOP_CONTINUE:.*]]
// CHECK:       [[LOOP_CONTINUE]]:
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr @_D6unwind6globalk, align 4
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i32 [[TMP0]], 5
// CHECK-NEXT:    br i1 [[TMP1]], label %[[LOOP_BODY:.*]], label %[[LOOP_EXIT:.*]]
// CHECK:       [[LOOP_BODY]]:
// CHECK-NEXT:    [[TMP2:%.*]] = add nuw nsw i32 [[TMP0]], 1
// CHECK-NEXT:    store i32 [[TMP2]], ptr @_D6unwind6globalk, align 4
// CHECK-NEXT:    invoke void @_D6unwind11doSomethingFMkZv(i32 [[TMP0]])
// CHECK-NEXT:            to label %[[LOOP_CONTINUE]] unwind label %[[LANDINGPAD:.*]]
// CHECK:       [[LOOP_EXIT]]:
// CHECK-NEXT:    ret void
// CHECK:       [[LANDINGPAD]]:
// CHECK-NEXT:    [[TMP3:%.*]] = landingpad { ptr, i32 }
// CHECK-NEXT:            cleanup
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr @_D6unwind6globalk, align 4
// CHECK-NEXT:    [[TMP5:%.*]] = add i32 [[TMP4]], -1
// CHECK-NEXT:    store i32 [[TMP5]], ptr @_D6unwind6globalk, align 4
// CHECK-NEXT:    resume { ptr, i32 } [[TMP3]]
//
void failure() {
	while (global < 5) {
		scope(failure) global--;

		doSomething(global++);
	}
}

// CHECK-LABEL: define void @_D6unwind4bothFMZv(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] personality ptr @__sd_eh_personality {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[DOTPR:%.*]] = load i32, ptr @_D6unwind6globalk, align 4
// CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i32 [[DOTPR]], 5
// CHECK-NEXT:    br i1 [[TMP0]], label %[[LOOP_BODY:.*]], label %[[LOOP_EXIT:.*]]
// CHECK:       [[LOOP_BODY]]:
// CHECK-NEXT:    [[TMP1:%.*]] = phi i32 [ [[TMP3:%.*]], %[[CLEANUP:.*]] ], [ [[DOTPR]], %[[ENTRY]] ]
// CHECK-NEXT:    invoke void @_D6unwind11doSomethingFMkZv(i32 [[TMP1]])
// CHECK-NEXT:            to label %[[CLEANUP]] unwind label %[[LANDINGPAD:.*]]
// CHECK:       [[CLEANUP]]:
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr @_D6unwind6globalk, align 4
// CHECK-NEXT:    [[TMP3]] = add i32 [[TMP2]], 1
// CHECK-NEXT:    store i32 [[TMP3]], ptr @_D6unwind6globalk, align 4
// CHECK-NEXT:    [[TMP4:%.*]] = icmp ult i32 [[TMP3]], 5
// CHECK-NEXT:    br i1 [[TMP4]], label %[[LOOP_BODY]], label %[[LOOP_EXIT]]
// CHECK:       [[LOOP_EXIT]]:
// CHECK-NEXT:    ret void
// CHECK:       [[LANDINGPAD]]:
// CHECK-NEXT:    [[TMP5:%.*]] = landingpad { ptr, i32 }
// CHECK-NEXT:            cleanup
// CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr @_D6unwind6globalk, align 4
// CHECK-NEXT:    [[TMP7:%.*]] = add i32 [[TMP6]], -1
// CHECK-NEXT:    store i32 [[TMP7]], ptr @_D6unwind6globalk, align 4
// CHECK-NEXT:    resume { ptr, i32 } [[TMP5]]
//
void both() {
	while (global < 5) {
		scope(failure) global--;
		scope(success) global++;

		doSomething(global);
	}
}
