// NOTE: Assertions have been autogenerated by tools/update_sdc_test_checks.py UTC_ARGS: --version 6
// RUN: %sdc %s -O2 -S --emit-llvm -o - | FileCheck %s
module virtualdispatch;

class A {
	// CHECK-LABEL: define noundef i8 @_D15virtualdispatch1A3fooFC15virtualdispatch1AZa(
	// CHECK-SAME: ptr nofree readnone captures(none) [[THIS:%.*]]) #[[ATTR0:[0-9]+]] {
	// CHECK-NEXT:  [[ENTRY:.*:]]
	// CHECK-NEXT:    ret i8 65
	//
	char foo() {
		return 'A';
	}

	// CHECK-LABEL: define noundef i32 @_D15virtualdispatch1A3barFC15virtualdispatch1AZk(
	// CHECK-SAME: ptr nofree readnone captures(none) [[THIS:%.*]]) #[[ATTR0]] {
	// CHECK-NEXT:  [[ENTRY:.*:]]
	// CHECK-NEXT:    ret i32 -1
	//
	uint bar() {
		return -1;
	}
}

// CHECK-LABEL: define ptr @_D15virtualdispatch7typeidAFMC15virtualdispatch1AZC6object9ClassInfo(
// CHECK-SAME: ptr nofree readonly captures(none) [[ARG_A:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[ARG_A]], align 8
// CHECK-NEXT:    ret ptr [[TMP0]]
//
auto typeidA(A a) {
	return typeid(a);
}

// CHECK-LABEL: define i8 @_D15virtualdispatch4fooAFMC15virtualdispatch1AZa(
// CHECK-SAME: ptr [[ARG_A:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[ARG_A]], align 8
// CHECK-NEXT:    [[VTBL:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP0]], i64 24
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[VTBL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i8 [[TMP1]](ptr nonnull [[ARG_A]])
// CHECK-NEXT:    ret i8 [[TMP2]]
//
auto fooA(A a) {
	return a.foo();
}

// CHECK-LABEL: define i32 @_D15virtualdispatch4barAFMC15virtualdispatch1AZk(
// CHECK-SAME: ptr [[ARG_A:%.*]]) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[ARG_A]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP0]], i64 32
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[TMP1]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i32 [[TMP2]](ptr nonnull [[ARG_A]])
// CHECK-NEXT:    ret i32 [[TMP3]]
//
auto barA(A a) {
	return a.bar();
}

class B : A {
	// CHECK-LABEL: define noundef i8 @_D15virtualdispatch1B3fooFC15virtualdispatch1BZa(
	// CHECK-SAME: ptr nofree readnone captures(none) [[THIS:%.*]]) #[[ATTR0]] {
	// CHECK-NEXT:  [[ENTRY:.*:]]
	// CHECK-NEXT:    ret i8 66
	//
	override char foo() {
		return 'B';
	}

	// CHECK-LABEL: define noundef i32 @_D15virtualdispatch1B3barFC15virtualdispatch1BZk(
	// CHECK-SAME: ptr nofree readnone captures(none) [[THIS:%.*]]) #[[ATTR0]] {
	// CHECK-NEXT:  [[ENTRY:.*:]]
	// CHECK-NEXT:    ret i32 42
	//
	final override uint bar() {
		return 42;
	}
}

// CHECK-LABEL: define ptr @_D15virtualdispatch7typeidBFMC15virtualdispatch1BZC6object9ClassInfo(
// CHECK-SAME: ptr nofree readonly captures(none) [[ARG_B:%.*]]) local_unnamed_addr #[[ATTR1]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[ARG_B]], align 8
// CHECK-NEXT:    ret ptr [[TMP0]]
//
auto typeidB(B b) {
	return typeid(b);
}

// CHECK-LABEL: define i8 @_D15virtualdispatch4fooBFMC15virtualdispatch1BZa(
// CHECK-SAME: ptr [[ARG_B:%.*]]) local_unnamed_addr #[[ATTR2]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[ARG_B]], align 8
// CHECK-NEXT:    [[VTBL:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP0]], i64 24
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[VTBL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i8 [[TMP1]](ptr nonnull [[ARG_B]])
// CHECK-NEXT:    ret i8 [[TMP2]]
//
auto fooB(B b) {
	return b.foo();
}

// CHECK-LABEL: define noundef i32 @_D15virtualdispatch4barBFMC15virtualdispatch1BZk(
// CHECK-SAME: ptr nofree readnone captures(none) [[ARG_B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret i32 42
//
auto barB(B b) {
	return b.bar();
}

final class C : B {
	// CHECK-LABEL: define noundef i8 @_D15virtualdispatch1C3fooFC15virtualdispatch1CZa(
	// CHECK-SAME: ptr nofree readnone captures(none) [[THIS:%.*]]) #[[ATTR0]] {
	// CHECK-NEXT:  [[ENTRY:.*:]]
	// CHECK-NEXT:    ret i8 67
	//
	override char foo() {
		return 'C';
	}
}

// CHECK-LABEL: define noundef nonnull ptr @_D15virtualdispatch7typeidCFMC15virtualdispatch1CZC6object9ClassInfo(
// CHECK-SAME: ptr nofree readnone captures(none) [[ARG_C:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret ptr @C15virtualdispatch1C.vtbl
//
auto typeidC(C c) {
	return typeid(c);
}

// CHECK-LABEL: define noundef i8 @_D15virtualdispatch4fooCFMC15virtualdispatch1CZa(
// CHECK-SAME: ptr nofree readnone captures(none) [[ARG_C:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret i8 67
//
auto fooC(C c) {
	return c.foo();
}

// CHECK-LABEL: define noundef i32 @_D15virtualdispatch4barCFMC15virtualdispatch1CZk(
// CHECK-SAME: ptr nofree readnone captures(none) [[ARG_C:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret i32 42
//
auto barC(C c) {
	return c.bar();
}
