#!/usr/bin/env bash

set -euo pipefail

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
cd "$SCRIPTDIR"

ROOTDIR=$(git rev-parse --show-toplevel)
cd "$ROOTDIR"

FILES=$(git diff --name-only "$(git merge-base master HEAD^)" | grep -e "\.d$" || true)
TOTAL=$(echo "${FILES}" | wc -w)

if [[ "$TOTAL" == 0 ]]; then
	echo "No files to format."
	exit 0
fi

echo Building sdfmt...
make -j bin/sdfmt

COUNTER=0
process_file() {
	FILE=$1
	echo "Formatting ${FILE}"

	bin/sdfmt -i "$FILE"

	if [[ -t 1 ]]; then
		printf "%u/%u\r" $(( ++COUNTER )) "$TOTAL"
	fi
}
export -f process_file

if [ $# -ge 1 ] && [ "$1" == "--no-parallel" ] ; then
	echo "Using non-parallel batch processing mode"
    for fn in $FILES; do process_file $fn; done

elif command -v parallel &> /dev/null; then
    parallel process_file ::: "$FILES"

else
	echo -e "Error:\tCannot locate 'parallel'."
	echo -e "      \tPass --no-parallel to fall back to slow batch processing instead."
	echo -e "      \t\t${0} --no-parallel"
fi
