#!/usr/bin/env python3
"""
update_sdc_test_checks.py - regenerate FileCheck lines for SDC LLVM IR tests.

Modeled on LLVM's update_llc_test_checks.py / update_test_checks.py, but
tailored to SDC's lit tests (test/llvm/*.d), whose RUN lines look like:

    // RUN: %sdc %s -S --emit-llvm -o - | FileCheck %s

For every function that already has a `// PREFIX-LABEL: <mangled>` line in
the test, the script runs sdc, extracts the function's IR, and rewrites the
PREFIX check lines for that function. Functions without a label are left
alone, so the test author controls which functions are checked.

Multiple RUN lines with `--check-prefix` are supported (see genmain.d):
each prefix's checks are regenerated from that prefix's RUN variant.

Following LLVM's update_test_checks.py: tests without any note are
onboarded (their checks are generated and the note is added); tests with
this tool's note are regenerated; tests with another tool's note are
skipped unless --force is given; tests with `// NOTE: Do not autogenerate`
(LLVM's UTC_AVOID) are always skipped. Pass --update-only to restrict
processing to already-managed tests.

Tests compiled with -g (e.g. dbg.d) are skipped: debug metadata
(DILocation line numbers, metadata numbering) needs hand-maintained checks;
auto-generating them would pin volatile values and sever the links between
the function bodies and the hand-written metadata CHECK-DAGs.

Unstable numeric SSA values (%1, %2, ...) become FileCheck variables
([[TMP1:%[0-9]+]], ...); named values (%arr, %s), block labels and globals
are kept literal.

Usage:
    tools/update_sdc_test_checks.py [--sdc-bin PATH] [--check] [--force] <test>...
"""

import argparse
import glob
import os
import re
import subprocess
import sys
import tempfile
import traceback

# Notes marking a test as managed by this tool. The old location is
# recognized so tests generated before the script moved to tools/ keep
# working; they are migrated to the new note on rewrite.
AUTOGEN_NOTES = (
    "// NOTE: Assertions have been autogenerated by " "tools/update_sdc_test_checks.py",
    "// NOTE: Assertions have been autogenerated by "
    "test/llvm/update_sdc_test_checks.py",
)
AUTOGEN_NOTE = AUTOGEN_NOTES[0]
# Explicit opt-out, like LLVM's UTC_AVOID.
DO_NOT_AUTOGENERATE = "// NOTE: Do not autogenerate"

RUN_RE = re.compile(r"^\s*//\s*RUN:\s*(.*?)\s*\|\s*FileCheck(.*)$")
PREFIX_RE = re.compile(r"--check-prefix(?:es)?[= ](\S+)")
NUMERIC_SSA_RE = re.compile(r"%([0-9]+)\b")
DEFINE_RE = re.compile(r"^define\b.*?@(\S+?)\(")
# CHECK-LABELs sometimes carry the full signature, e.g.
# "// CHECK-LABEL: define %S @_D9structabi1S6__ctorFMS9structabi1SmZS9structabi1S".
# Fall back to extracting the @name in that case.
LABEL_FUNC_RE = re.compile(r"@(\S+?)(?:[\s(]|$)")
# sdc debug flag: -g on its own, not part of another flag.
DEBUG_FLAG_RE = re.compile(r"(?:^|\s)-g(?:\s|$)")

# (pattern, replacement) applied to generated CHECK lines for values that
# are not stable across test edits, e.g. source line numbers baked into
# the IR by the compiler.
VOLATILE_RES = [
    # Array bounds failure calls carry the source line number.
    (
        re.compile(
            r"(call void @__sd_array_outofbounds"
            r"\(\{ i64, ptr \} \{ i64 [0-9]+, ptr @\.str \}, )"
            r"i32 [0-9]+(\))"
        ),
        r"\1i32 {{[0-9]+}}\2",
    ),
]


def warn(msg):
    print("warning: %s" % msg, file=sys.stderr)


def label_re(prefix):
    return re.compile(r"^(\s*)//\s*%s-LABEL:\s*(.+?)\s*$" % re.escape(prefix))


def owned_check_re(prefix):
    # Matches the plain check directives owned by the tool for this prefix:
    # `// PREFIX:` and `// PREFIX-LABEL:`, but not `// PREFIX-NOT:` etc.,
    # which are considered hand-maintained.
    return re.compile(r"^\s*//\s*%s(-LABEL)?:(?!-)" % re.escape(prefix))


def parse_run_lines(lines):
    """Return [(sdc_cmd, [prefixes])] for each RUN line piping to FileCheck."""
    runs = []
    for line in lines:
        m = RUN_RE.match(line)
        if not m:
            continue
        prefixes = []
        for pm in PREFIX_RE.finditer(m.group(2)):
            prefixes.extend(pm.group(1).split(","))
        runs.append((m.group(1), prefixes or ["CHECK"]))
    return runs


def get_substitutions(test_path):
    # Lit-like substitutions. %s is the absolute test path; like lit
    # (test_exec_root == test_source_root), the tool command runs with
    # cwd set to the test's directory, which sdc requires for its
    # module/package <-> directory matching.
    test_path = os.path.abspath(test_path)
    test_dir = os.path.dirname(test_path)
    return [
        ("%s", test_path),
        ("%S", test_dir),
        ("%p", test_dir),
    ]


def apply_substitutions(cmd, substitutions):
    for old, new in substitutions:
        cmd = cmd.replace(old, new)
    return cmd


def run_sdc(sdc_bin, test_path, run_cmd):
    """Run the test's RUN line (up to the FileCheck pipe) and return IR."""
    # Substitute %sdc first: %s is a prefix of %sdc, so the lit
    # substitutions below would otherwise corrupt it.
    cmd = run_cmd.replace("%sdc", sdc_bin)
    substitutions = get_substitutions(test_path)
    cmd = apply_substitutions(cmd, substitutions)
    test_dir = os.path.dirname(os.path.abspath(test_path))
    # Run with cwd set to the test's directory (like lit does); sdc
    # requires the module declaration to match the directory hierarchy.
    # Capture raw bytes: some RUN lines (e.g. `-c --emit-llvm`) produce
    # binary output that isn't valid UTF-8.
    result = subprocess.run(
        cmd, shell=True, cwd=test_dir, stdout=subprocess.PIPE, stderr=subprocess.PIPE
    )
    if result.returncode != 0:
        raise RuntimeError(
            "sdc failed on %s:\n%s"
            % (test_path, result.stderr.decode("utf-8", errors="replace"))
        )
    if b"\x00" in result.stdout:
        raise RuntimeError(
            "sdc emitted binary output on %s; this tool can only "
            "regenerate checks from textual IR (use -S --emit-llvm)" % test_path
        )
    return result.stdout.decode("utf-8", errors="replace")


def strip_ir_comment(line):
    """Remove the `;` comment from an IR line, if any.

    A naive split on `;` would corrupt string literals containing `;`
    (e.g. `@.str = ... c"a;b"`), so only a `;` outside a double-quoted
    string starts a comment.
    """
    in_string = False
    i = 0
    while i < len(line):
        ch = line[i]
        if ch == '"' and (i == 0 or line[i - 1] != "\\"):
            in_string = not in_string
        elif ch == ";" and not in_string:
            return line[:i].rstrip()
        i += 1
    return line.rstrip()


def extract_functions(ir_text):
    """Map mangled function name -> list of IR body lines."""
    functions = {}
    current = None
    body = []
    for line in ir_text.splitlines():
        m = DEFINE_RE.match(line)
        if m:
            current = m.group(1)
            body = []
            continue
        if current is not None:
            if line.rstrip() == "}":
                functions[current] = body
                current = None
            else:
                stripped = strip_ir_comment(line)
                if stripped.strip():
                    body.append(stripped)
    return functions


def make_check_lines(prefix, body_lines):
    """Turn IR body lines into PREFIX check lines with var substitution."""
    var_map = {}
    counter = [0]
    seen = set()
    check_lines = []
    for line in body_lines:
        stripped = line.strip()

        def sub(m):
            num = m.group(1)
            if num not in var_map:
                counter[0] += 1
                var_map[num] = "TMP%d" % counter[0]
            name = var_map[num]
            if num in seen:
                return "[[%s]]" % name
            seen.add(num)
            return "[[%s:%%[0-9]+]]" % name

        checked = NUMERIC_SSA_RE.sub(sub, stripped)
        for pattern, replacement in VOLATILE_RES:
            checked = pattern.sub(replacement, checked)
        check_lines.append("// %s: %s" % (prefix, checked))
    return check_lines


def find_var_uses(line):
    """Variables referenced as [[NAME]] or [[NAME:...]] in a check line."""
    return set(re.findall(r"\[\[([A-Za-z_][A-Za-z0-9_]*)", line))


def find_var_defs(line):
    """Variables defined as [[NAME:...]] in a check line."""
    return set(re.findall(r"\[\[([A-Za-z_][A-Za-z0-9_]*):", line))


def process_prefix(lines, prefix, functions, ir_text):
    """Regenerate this prefix's checks. Returns the new line list."""
    lre = label_re(prefix)
    cre = owned_check_re(prefix)

    # Locate existing PREFIX-LABELs.
    labels = []  # (line_index, indent, raw_label, func_name)
    for i, line in enumerate(lines):
        m = lre.match(line)
        if m:
            raw, name = m.group(2), m.group(2)
            if name not in functions:
                # Maybe a full-signature label; extract @name.
                fm = LABEL_FUNC_RE.search(m.group(0))
                if fm:
                    name = fm.group(1)
            labels.append((i, m.group(1), raw, name))

    new_lines = []
    pos = 0
    for li, (idx, indent, raw, name) in enumerate(labels):
        # A label pattern that matches more than once in the IR (e.g. a
        # bare function name that also appears in a call before its
        # definition) makes FileCheck match the wrong location. Warn and
        # suggest anchoring, e.g. `// CHECK-LABEL: define {{.*}} @foo(`.
        if sum(1 for _ in re.finditer(re.escape(raw), ir_text)) > 1:
            warn(
                "label '%s' matches multiple times in the IR; consider "
                "anchoring it like '// %s-LABEL: define {{.*}} @%s('"
                % (raw, prefix, name)
            )
        end = labels[li + 1][0] if li + 1 < len(labels) else len(lines)
        new_lines.extend(lines[pos:idx])
        if name in functions:
            generated = [indent + g for g in make_check_lines(prefix, functions[name])]
            region = lines[idx:end]
            owned = [l for l in region[1:] if cre.match(l)]
            kept = [l for l in region[1:] if not cre.match(l)]
            # Hand-maintained lines (e.g. CHECK-DAG, CHECK-NOT) are kept,
            # but if they reference variables defined in the checks being
            # replaced (e.g. pgo.d's CHECK-DAG uses [[LIKELY]] defined in
            # a CHECK line), replacing would leave dangling references.
            # The tool can't preserve the author's variable scheme, so
            # leave such functions alone.
            old_defs = set()
            for l in owned:
                old_defs |= find_var_defs(l)
            kept_uses = set()
            for l in kept:
                kept_uses |= find_var_uses(l)
            gen_defs = set()
            for g in generated:
                gen_defs |= find_var_defs(g)
            dangling = (kept_uses & old_defs) - gen_defs
            if dangling:
                warn(
                    "function %s: kept %s checks reference %s defined in "
                    "replaced checks; leaving function alone"
                    % (name, prefix, ", ".join(sorted("[[%s]]" % v for v in dangling)))
                )
                new_lines.extend(lines[idx:end])
            else:
                new_lines.extend([lines[idx]] + generated + kept)
        else:
            warn(
                "function %s not in sdc output, leaving %s checks alone"
                % (name, prefix)
            )
            new_lines.extend(lines[idx:end])
        pos = end
    new_lines.extend(lines[pos:])
    return new_lines, bool(labels)


def find_filecheck():
    """Locate FileCheck on PATH."""
    for d in os.environ.get("PATH", "").split(os.pathsep):
        p = os.path.join(d, "FileCheck")
        if os.path.isfile(p) and os.access(p, os.X_OK):
            return p
    return None


def classify_test(test_path):
    """Return (status, reason) describing whether the tool manages a test.

    Statuses: "managed", "avoid" (explicit opt-out), "foreign" (another
    tool's note), "unmanaged" (no note).
    """
    with open(test_path) as f:
        first_line = f.readline()
    if DO_NOT_AUTOGENERATE in first_line:
        return ("avoid", "explicitly opted out (%s)" % DO_NOT_AUTOGENERATE)
    for note in AUTOGEN_NOTES:
        if note in first_line:
            return ("managed", "")
    if "NOTE: Assertions have been autogenerated by" in first_line:
        return ("foreign", "managed by another tool; use --force to take over")
    return ("unmanaged", "not managed by this tool; use --force to manage it")


def process_test(test_path, sdc_bin, filecheck, check_only=False):
    with open(test_path) as f:
        lines = f.read().splitlines()

    runs = parse_run_lines(lines)
    if not runs:
        warn("no RUN line with FileCheck in %s, skipping" % test_path)
        return False

    if any(DEBUG_FLAG_RE.search(cmd) for cmd, _ in runs):
        warn(
            "%s: skipping: tests compiled with -g need hand-maintained "
            "checks (debug metadata is not auto-generated)" % test_path
        )
        return False

    # Run each variant once; several prefixes may share one RUN line.
    # Variants producing binary output (e.g. `-c --emit-llvm`) are
    # skipped with a warning; their prefixes keep their existing checks.
    ir_by_cmd = {}
    skipped_cmds = set()
    for cmd, _ in runs:
        if cmd in ir_by_cmd or cmd in skipped_cmds:
            continue
        try:
            ir_text = run_sdc(sdc_bin, test_path, cmd)
        except RuntimeError as e:
            if "binary output" in str(e):
                warn("%s: skipping RUN variant with binary output" % test_path)
                skipped_cmds.add(cmd)
                continue
            raise
        ir_by_cmd[cmd] = (ir_text, extract_functions(ir_text))

    if not ir_by_cmd:
        warn("%s: no usable IR output, nothing to do" % test_path)
        return False

    new_lines = lines
    any_labels = False
    for cmd, prefixes in runs:
        if cmd in skipped_cmds:
            continue
        ir_text, functions = ir_by_cmd[cmd]
        for prefix in prefixes:
            new_lines, had_labels = process_prefix(
                new_lines, prefix, functions, ir_text
            )
            any_labels = any_labels or had_labels

    if not any_labels:
        warn("%s: no CHECK-LABELs, nothing to do" % test_path)
        return False

    # Add the regeneration note if missing; migrate a stale note from
    # the old script location to the current one.
    old_note = AUTOGEN_NOTES[1]
    new_lines = [
        l.replace(old_note, AUTOGEN_NOTE) if old_note in l else l for l in new_lines
    ]
    if not any(AUTOGEN_NOTE in l for l in new_lines):
        new_lines = [AUTOGEN_NOTE] + new_lines

    changed = new_lines != lines

    if changed and not check_only:
        new_content = "\n".join(new_lines) + "\n"
        # Self-check before committing: verify every RUN variant against
        # its own IR using a temp file. A failed self-check means the
        # tool generated inconsistent checks (e.g. a volatile value it
        # didn't normalize); the original file is left untouched and the
        # failure is reported.
        if filecheck is None:
            warn("FileCheck not found, skipping self-check")
        else:
            test_dir = os.path.dirname(os.path.abspath(test_path))
            fd, tmp_path = tempfile.mkstemp(suffix=".d", dir=test_dir)
            try:
                with os.fdopen(fd, "w") as tmp:
                    tmp.write(new_content)
                for cmd, prefixes in runs:
                    if cmd in skipped_cmds:
                        continue
                    verify = subprocess.run(
                        [filecheck, "--check-prefixes=" + ",".join(prefixes), tmp_path],
                        input=ir_by_cmd[cmd][0],
                        stdout=subprocess.PIPE,
                        stderr=subprocess.PIPE,
                        text=True,
                        cwd=test_dir,
                    )
                    if verify.returncode != 0:
                        raise RuntimeError(
                            "%s: regenerated %s checks FAIL FileCheck "
                            "(file left unchanged):\n%s"
                            % (test_path, ",".join(prefixes), verify.stderr)
                        )
            finally:
                os.unlink(tmp_path)
        with open(test_path, "w") as f:
            f.write(new_content)
    return changed


def main():
    parser = argparse.ArgumentParser(
        description="Regenerate FileCheck lines in SDC LLVM IR tests."
    )
    parser.add_argument("tests", nargs="+", help="test files to update")
    parser.add_argument("--sdc-bin", default=None, help="path to the sdc binary")
    parser.add_argument(
        "--check",
        action="store_true",
        help="don't modify files; exit 1 if any would change",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="take over tests managed by another tool "
        "(by default those are skipped)",
    )
    parser.add_argument(
        "--update-only",
        action="store_true",
        help="only process tests already managed by this "
        "tool (by default unmarked tests are onboarded)",
    )
    args = parser.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    sdc_bin = args.sdc_bin or os.path.join(script_dir, "../bin/sdc")
    sdc_bin = os.path.abspath(sdc_bin)
    if not os.path.isfile(sdc_bin):
        print("error: sdc binary not found: %s" % sdc_bin, file=sys.stderr)
        return 1

    filecheck = find_filecheck()

    # Expand globs (like LLVM's update scripts) so patterns work
    # regardless of shell expansion.
    tests = []
    for pattern in args.tests:
        expanded = glob.glob(pattern)
        if not expanded:
            warn("test file pattern '%s' was not found, ignoring it" % pattern)
            continue
        tests.extend(sorted(expanded))

    returncode = 0
    counts = {"updated": 0, "unchanged": 0, "skipped": 0, "failed": 0}
    for test in tests:
        try:
            status, reason = classify_test(test)
            if status == "avoid":
                print("%s: skipped (%s)" % (test, reason))
                counts["skipped"] += 1
                continue
            if status == "foreign" and not args.force:
                print("%s: skipped (%s)" % (test, reason))
                counts["skipped"] += 1
                continue
            if status == "unmanaged" and args.update_only:
                print("%s: skipped (not managed by this tool)" % test)
                counts["skipped"] += 1
                continue
            # "managed", "unmanaged" (onboarded by default, like LLVM),
            # and "foreign" with --force: process the test.
            changed = process_test(test, sdc_bin, filecheck, check_only=args.check)
        except Exception:
            print("error: failed to update test %s" % test, file=sys.stderr)
            traceback.print_exc()
            counts["failed"] += 1
            returncode = 1
            continue
        if changed:
            counts["updated"] += 1
            print("%s: updated" % test)
        else:
            counts["unchanged"] += 1
            print("%s: no changes" % test)

    print(
        "done: %d updated, %d unchanged, %d skipped, %d failed"
        % (counts["updated"], counts["unchanged"], counts["skipped"], counts["failed"])
    )

    if args.check and counts["updated"]:
        return 1
    return returncode


if __name__ == "__main__":
    sys.exit(main())
